export const INGREDIENTS_LIST = [
  'Chicken Breast', 'Chicken Thighs', 'Minced Beef', 'Salmon Fillet', 'Prawns',
  'Bacon', 'Sausages', 'Lamb Chops', 'Pork Chops', 'Turkey Mince',
  'Tofu', 'Eggs', 'Cheddar Cheese', 'Mozzarella', 'Cream Cheese',
  'Butter', 'Milk', 'Double Cream', 'Yoghurt', 'Parmesan',
  'Rice', 'Pasta', 'Bread', 'Noodles', 'Flour',
  'Potatoes', 'Sweet Potatoes', 'Onions', 'Garlic', 'Tomatoes',
  'Peppers', 'Mushrooms', 'Spinach', 'Broccoli', 'Carrots',
  'Courgette', 'Aubergine', 'Avocado', 'Sweetcorn', 'Peas',
  'Green Beans', 'Lettuce', 'Cucumber', 'Celery', 'Cabbage',
  'Cauliflower', 'Kale', 'Beetroot', 'Leeks', 'Spring Onions',
  'Chilli', 'Ginger', 'Lemon', 'Lime', 'Coconut Milk',
  'Soy Sauce', 'Olive Oil', 'Vegetable Oil', 'Sesame Oil', 'Vinegar',
  'Honey', 'Maple Syrup', 'Stock Cubes', 'Tinned Tomatoes', 'Tomato Puree',
  'Chickpeas', 'Lentils', 'Black Beans', 'Kidney Beans', 'Baked Beans',
  'Peanut Butter', 'Almonds', 'Walnuts', 'Cashews', 'Pine Nuts',
  'Cumin', 'Paprika', 'Turmeric', 'Oregano', 'Basil',
  'Thyme', 'Rosemary', 'Cinnamon', 'Nutmeg', 'Coriander',
  'Chilli Flakes', 'Black Pepper', 'Salt', 'Bay Leaves', 'Curry Powder',
  'Plain Flour', 'Self-Raising Flour', 'Cornflour', 'Breadcrumbs', 'Oats',
  'Sugar', 'Brown Sugar', 'Icing Sugar', 'Vanilla Extract', 'Cocoa Powder',
  'Dark Chocolate', 'Bananas', 'Apples', 'Strawberries', 'Blueberries',
  'Mango', 'Pineapple', 'Orange', 'Cranberries', 'Raisins',
  'Tortilla Wraps', 'Pitta Bread', 'Naan Bread', 'Bagels', 'Croissants',
  'Mayonnaise', 'Ketchup', 'Mustard', 'Worcester Sauce', 'Hot Sauce',
  'Pesto', 'Hummus', 'Tahini', 'Fish Sauce', 'Oyster Sauce',
  'White Wine', 'Red Wine', 'Beer', 'Sherry', 'Brandy',
  'Anchovies', 'Tuna (Tinned)', 'Sardines', 'Cod', 'Haddock',
  'Chorizo', 'Salami', 'Ham', 'Prosciutto', 'Pancetta',
  'Feta Cheese', 'Goats Cheese', 'Brie', 'Halloumi', 'Ricotta',
  'Crème Fraîche', 'Soured Cream', 'Condensed Milk', 'Evaporated Milk', 'Coconut Cream',
  'Rocket', 'Watercress', 'Pak Choi', 'Asparagus', 'Artichokes',
  'Olives', 'Capers', 'Sun-Dried Tomatoes', 'Roasted Peppers', 'Jalapeños',
  'Gnocchi', 'Couscous', 'Quinoa', 'Bulgur Wheat', 'Polenta',
  'Lasagne Sheets', 'Egg Noodles', 'Rice Noodles', 'Soba Noodles', 'Vermicelli',
  'Baking Powder', 'Bicarbonate of Soda', 'Yeast', 'Gelatine', 'Agar',
  'Maple Bacon', 'Truffle Oil', 'Miso Paste', 'Harissa', 'Gochujang',
  'Tamarind Paste', 'Pomegranate Seeds', 'Edamame', 'Tempeh', 'Seitan',
  'Nutritional Yeast', 'Flaxseed', 'Chia Seeds', 'Pumpkin Seeds', 'Sunflower Seeds',
  'Dried Apricots', 'Dates', 'Figs', 'Prunes', 'Mixed Nuts',
];

export const DIETARY_OPTIONS = [
  { value: '', label: 'No Preference' },
  { value: 'vegetarian', label: 'Vegetarian' },
  { value: 'vegan', label: 'Vegan' },
  { value: 'gluten-free', label: 'Gluten-Free' },
  { value: 'dairy-free', label: 'Dairy-Free' },
  { value: 'keto', label: 'Keto' },
  { value: 'paleo', label: 'Paleo' },
  { value: 'halal', label: 'Halal' },
  { value: 'kosher', label: 'Kosher' },
];

export const CUISINE_OPTIONS = [
  { value: '', label: 'Any Cuisine' },
  { value: 'british', label: 'British' },
  { value: 'italian', label: 'Italian' },
  { value: 'indian', label: 'Indian' },
  { value: 'chinese', label: 'Chinese' },
  { value: 'japanese', label: 'Japanese' },
  { value: 'thai', label: 'Thai' },
  { value: 'mexican', label: 'Mexican' },
  { value: 'french', label: 'French' },
  { value: 'mediterranean', label: 'Mediterranean' },
  { value: 'middle-eastern', label: 'Middle Eastern' },
  { value: 'american', label: 'American' },
  { value: 'korean', label: 'Korean' },
];

export const COOKING_TIME_OPTIONS = [
  { value: 15, label: 'Under 15 mins', description: 'Quick & easy' },
  { value: 30, label: 'Under 30 mins', description: 'Weeknight friendly' },
  { value: 60, label: 'Under 1 hour', description: 'Worth the wait' },
  { value: 120, label: '1+ hours', description: 'Slow cook masterpiece' },
];

export const SKILL_LEVEL_OPTIONS = [
  { value: 'beginner', label: 'Beginner', description: 'Simple techniques, basic equipment' },
  { value: 'intermediate', label: 'Intermediate', description: 'Some cooking experience' },
  { value: 'advanced', label: 'Advanced', description: 'Complex techniques welcome' },
];

export const MEAL_KIT_PARTNERS = [
  {
    name: 'HelloFresh',
    logo: '🟢',
    description: 'The UK\'s most popular meal kit',
    url: 'https://www.hellofresh.co.uk',
    discount: 'Get 60% off your first box',
    color: '#91C11E',
  },
  {
    name: 'Gousto',
    logo: '🔵',
    description: 'Over 250 recipes per month',
    url: 'https://www.gousto.co.uk',
    discount: '65% off first box + 30% off first month',
    color: '#00A0E3',
  },
  {
    name: 'Mindful Chef',
    logo: '🟣',
    description: 'Healthy, gluten-free meals',
    url: 'https://www.mindfulchef.com',
    discount: '25% off your first 4 boxes',
    color: '#6B4C9A',
  },
  {
    name: 'Green Chef',
    logo: '🌿',
    description: 'Organic & sustainable ingredients',
    url: 'https://www.greenchef.co.uk',
    discount: '55% off first box',
    color: '#2D7D3E',
  },
];

export const SUPERMARKET_PARTNERS = [
  {
    name: 'Tesco',
    logo: '🔴',
    description: 'Groceries delivered to your door',
    url: 'https://www.tesco.com/groceries',
    color: '#00539F',
  },
  {
    name: 'Sainsbury\'s',
    logo: '🟠',
    description: 'Quality food, fairly priced',
    url: 'https://www.sainsburys.co.uk/groceries',
    color: '#F06C00',
  },
  {
    name: 'Ocado',
    logo: '🟢',
    description: 'Smart online grocery shopping',
    url: 'https://www.ocado.com',
    color: '#6F2B91',
  },
  {
    name: 'Amazon Fresh',
    logo: '📦',
    description: 'Fast delivery, great prices',
    url: 'https://www.amazon.co.uk/fresh',
    color: '#FF9900',
  },
];

export const SAMPLE_RECIPES = [
  {
    id: 'sample-1',
    title: 'Creamy Garlic Chicken Pasta',
    description: 'A rich and creamy pasta dish with tender chicken and a garlicky sauce.',
    image_emoji: '🍝',
    cooking_time: 25,
    skill_level: 'beginner',
    dietary_tags: [],
    average_rating: 4.8,
    rating_count: 124,
    servings: 4,
  },
  {
    id: 'sample-2',
    title: 'Thai Green Curry',
    description: 'Aromatic coconut curry with crisp vegetables and fragrant herbs.',
    image_emoji: '🍛',
    cooking_time: 30,
    skill_level: 'intermediate',
    dietary_tags: ['gluten-free', 'dairy-free'],
    average_rating: 4.7,
    rating_count: 98,
    servings: 4,
  },
  {
    id: 'sample-3',
    title: 'Classic Beef Burger',
    description: 'Juicy homemade burgers with all the trimmings and secret sauce.',
    image_emoji: '🍔',
    cooking_time: 20,
    skill_level: 'beginner',
    dietary_tags: [],
    average_rating: 4.9,
    rating_count: 256,
    servings: 4,
  },
  {
    id: 'sample-4',
    title: 'Mediterranean Veggie Bowl',
    description: 'A colourful bowl packed with roasted veg, hummus, and feta.',
    image_emoji: '🥗',
    cooking_time: 35,
    skill_level: 'beginner',
    dietary_tags: ['vegetarian'],
    average_rating: 4.6,
    rating_count: 87,
    servings: 2,
  },
  {
    id: 'sample-5',
    title: 'Japanese Ramen',
    description: 'Rich pork broth with noodles, soft-boiled egg, and spring onions.',
    image_emoji: '🍜',
    cooking_time: 90,
    skill_level: 'advanced',
    dietary_tags: ['dairy-free'],
    average_rating: 4.9,
    rating_count: 178,
    servings: 2,
  },
  {
    id: 'sample-6',
    title: 'Vegan Chocolate Brownies',
    description: 'Fudgy, rich brownies that nobody will believe are plant-based.',
    image_emoji: '🍫',
    cooking_time: 40,
    skill_level: 'beginner',
    dietary_tags: ['vegan', 'dairy-free'],
    average_rating: 4.8,
    rating_count: 145,
    servings: 12,
  },
];
