import { ChefHat } from 'lucide-react';
import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-300">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-2 md:grid-cols-5 gap-8">
          {/* Brand */}
          <div className="col-span-2 md:col-span-1">
            <div className="flex items-center gap-2 mb-4">
              <ChefHat className="w-7 h-7 text-brand-orange" />
              <span className="text-lg font-bold text-white font-heading">Cheffy</span>
            </div>
            <p className="text-sm text-gray-400">
              Turn your ingredients into delicious meals with AI-powered recipe generation.
            </p>
          </div>

          {/* Product */}
          <div>
            <h4 className="text-sm font-semibold text-white mb-3">Product</h4>
            <ul className="space-y-2 text-sm">
              <li><Link href="/#how-it-works" className="hover:text-white transition-colors">How It Works</Link></li>
              <li><Link href="/#recipes" className="hover:text-white transition-colors">Sample Recipes</Link></li>
              <li><Link href="/#partners" className="hover:text-white transition-colors">Partners</Link></li>
            </ul>
          </div>

          {/* Partners */}
          <div>
            <h4 className="text-sm font-semibold text-white mb-3">Partners</h4>
            <ul className="space-y-2 text-sm">
              <li><span className="text-gray-500 cursor-default">HelloFresh</span></li>
              <li><span className="text-gray-500 cursor-default">Gousto</span></li>
              <li><span className="text-gray-500 cursor-default">Tesco</span></li>
              <li><span className="text-gray-500 cursor-default">Sainsbury&apos;s</span></li>
            </ul>
          </div>

          {/* Company */}
          <div>
            <h4 className="text-sm font-semibold text-white mb-3">Company</h4>
            <ul className="space-y-2 text-sm">
              <li><span className="text-gray-500 cursor-default">About</span></li>
              <li><span className="text-gray-500 cursor-default">Blog</span></li>
              <li><span className="text-gray-500 cursor-default">Careers</span></li>
              <li><span className="text-gray-500 cursor-default">Contact</span></li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="text-sm font-semibold text-white mb-3">Legal</h4>
            <ul className="space-y-2 text-sm">
              <li><span className="text-gray-500 cursor-default">Privacy Policy</span></li>
              <li><span className="text-gray-500 cursor-default">Terms of Service</span></li>
              <li><span className="text-gray-500 cursor-default">Cookie Policy</span></li>
            </ul>
          </div>
        </div>

        <div className="border-t border-gray-800 mt-10 pt-8 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Cheffy. All rights reserved.
          </p>
          <p className="text-xs text-gray-600">
            Made with AI. Recipes generated by artificial intelligence. Always verify allergen information.
          </p>
        </div>
      </div>
    </footer>
  );
}
